### ISSUE TITLE
Context path not applying

### ISSUE THREAD

**Issue by zmnw** [matootie/github-docker#13]
When attempting to run this action using the context option, the builder is still trying to locate the Dockerfile in the root of the repo. I've tried many iterations of defining that variable since the documentation doesn't state how to define it, but it always seems that the docker build command attempts to locate the Dockerfile in the root. How should the context variable be defined to properly target a Dockerfile within a subfolder?

My current config:
```
name: Docker Image CI
on:
  push:
    paths:
    - subdir/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
    - name: Build and push image
      uses: matootie/github-docker@v2.1.0
      with:
        accessToken: ${{ secrets.BUILD_TOKEN }}
        context: subdir
        repositoryName: my-org/my-repo2
        imageName: docker_image
        imageTag: latest
```

Last run output error:
```
docker build --tag docker.pkg.github.com/my-org/my-repo2/docker_image:latest /home/runner/work/my-repo/my-repo
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/runner/work/my-repo/my-repo/Dockerfile: no such file or directory
```

I've attempted defining conext using the iterations below with no success:
* subdir
* subdir/
* ./subdir
* ./subdir/
