### ISSUE TITLE
How to use build arguments?

### ISSUE THREAD

**Issue by ThibaultVlacich** [matootie/github-docker#14]
I'm not really sure how to use the optional build arguments parameter.

First, in the readme you're saying `buildArguments`, but [in the code](https://github.com/matootie/github-docker/blob/master/index.js#L75) it's `buildArg` it seems like?

Second, what should be the syntax of `buildArg`? An example would be nice. Should it be like that:
```yml
jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Publish Image
        uses: matootie/github-docker@v2.2.1
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          buildArg:
            ARG1: ${{ secrets.ARG1 }}
            ARG2: ${{ secrets.ARG2 }}
```

EDIT: this syntax is invalid anyway so it's not that...

Or like that:
```yml
jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Publish Image
        uses: matootie/github-docker@v2.2.1
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          buildArg: |
            ARG1=${{ secrets.ARG1 }}
            ARG2=${{ secrets.ARG2 }}
```

EDIT: Also tried this, not working. It's sending all the text into a single `--build-arg` argument.

Or something else all together... I'm not the best with regex, so I can't really understand what's [the regex](https://github.com/matootie/github-docker/blob/master/index.js#L76) is supposed to parse.

**Comment by matootie** [comment]
Hello @ThibaultVlacich.

There's actually a mistake in the regex. I'm updating it to this:

```js
// Process the build args
let buildArg = [];
const buildArgsRaw = core.getInput('buildArg', { require: false });
if (buildArgsRaw) buildArg = buildArgsRaw.match(/\w+=\S+/g).flatMap(str => ["--build-arg", str]);
```

The regex pattern `/\w+=\S+/g` is quite simple. Take a look [here](https://regex101.com/r/G62ZP6/1) for an example.

This way, the intended use of the `buildArg` input is as you put in your post:

```yaml
        with:
          buildArg: |
            ARG1=${{ secrets.ARG1 }}
            ARG2=${{ secrets.ARG2 }}
```

As you can see, using [this workflow](https://github.com/matootie/github-docker/blob/v2.2.2/.github/workflows/test.yml), [the results](https://github.com/matootie/github-docker/runs/454299325?check_suite_focus=true#step:3:15) seem to be as intended. I've released a new patch with this fix. Make sure you use GitHub Docker version 2.2.2 from now on, like so:

```yaml
jobs:
  publish:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish Image
        uses: matootie/github-docker@v2.2.2
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          buildArg: |
            ARG1=${{ secrets.ARG1 }}
            ARG2=${{ secrets.ARG2 }}
```

I've also updated the `README.md` and `action.yml` with the correct name of the input, and added an example to help future users.
