### ISSUE TITLE
Docker fails to find Dockerfile - weird path?

### ISSUE THREAD

**Issue by khromov** [matootie/github-docker#2]
My workflow config:
https://github.com/khromov/docker-node-hello-world/blob/master/.github/workflows/main.yml

Failed build:
https://github.com/khromov/docker-node-hello-world/runs/362889904

The `docker build` line looks strange, specifically the path `/home/runner/work/docker-node-hello-world/docker-node-hello-world`. Should there really be two `docker-node-hello-world` folders?

**Comment by matootie** [comment]
Hi @khromov!

It looks like you're missing the checkout step! The worker needs to checkout your repository in order to have access to its contents *(including the Dockerfile)*.

All you need to do is update your workflow file to include this step, like so:

```yaml
name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: GitHub Docker Action
      uses: matootie/github-docker@v1.0.1
      with:
        # GitHub user to publish the image on behalf of.
        username: khromov
        # GitHub Personal Access Token for the user.
        personalAccessToken: ${{ secrets.ACCESS_TOKEN }}
        # The repository to push the image to. Defaults to current repository. Must be specified in format user/repo
        repositoryName: khromov/docker-node-hello-world # optional
        # The desired name for the image. Defaults to current repository name.
        imageName: docker-node-hello-world # optional
        # The desired tag for the image. Defaults to current branch or release version number.
        # imageTag: # optional
```

Hope this helps!
